/**
 * Default keywords for 2026 Hungarian election-related content.
 * Stored in chrome.storage.sync; users can add/remove via popup.
 */

var DEFAULT_KEYWORDS = [
  // Party names
  'fidesz',
  'kdnp',
  'tisza',
  'tisza part',
  'tisza párt',
  'dk',
  'demokratikus koalíció',
  'demokratikus koalicio',
  'mszp',
  'mi hazánk',
  'momentum',
  'lmp',
  'magyar kétfarkú kutya párt',
  'mkkp',
  'jobbik',
  'erős magyarország',
  'összefogás',
  'kormánypárt',
  'ellenzék',
  'ellenzeki',
  // Politicians
  'orbán',
  'orban',
  'magyar péter',
  'magyar peter',
  'gyurcsány',
  'gyurcsany',
  'jakab',
  'toroczkai',
  'donáth',
  'donath',
  'dobrev',
  'márki-zay',
  'marki-zay',
  'trócsányi',
  'trocsanyi',
  'hadházy',
  'hadhazy',
  'szél bernadett',
  'szel bernadett',
  'gelencsér',
  'varga judit',
  'hollik',
  'novak',
  'kövér',
  'kover',
  'szijjártó',
  'szijjarto',
  'vitézy',
  'vitezy',
  'ungár',
  'ungar',
  'lázár',
  'lazar',
  'kocsis máté',
  'kocsis mate',
  'rogán',
  'rogan',
  'nagy márton',
  'nagy marton',
  'navracsics',
  'sulyok tamás',
  'sulyok tamas',
  'deutsch tamás',
  'deutsch tamas',
  'menczer',
  'szentkirályi',
  'szentkiralyi',
  'tompos márton',
  'tompos marton',
  // Election terms
  'választás',
  'valasztas',
  'szavazás',
  'szavazas',
  'kampány',
  'kampany',
  'jelölt',
  'jelolt',
  'mandátum',
  'mandatum',
  'frakció',
  'frakcio',
  'koalíció',
  'koalicio',
  'listaállítás',
  'listaallitas',
  'előválasztás',
  'elovalasztas',
  'képviselő',
  'kepviselo',
  'országgyűlés',
  'orszaggyules',
  'parlament',
  'képviselőjelöltség',
  'kepviselojeloltseg',
  'egyéni képviselő',
  'egyeni kepviselo',
  'összesítő lista',
  'osszesito lista',
  'szavazatszámlálás',
  'szavazatszamlalas',
  'népszavazás',
  'nepszavazas',
  'referendum',
  '2026-os választás',
  '2026 os valasztas',
  // General political terms
  'politika',
  'miniszterelnök',
  'miniszterelnok',
  'kormány',
  'kormany',
  'törvény',
  'torveny',
  'törvényhozás',
  'torvenyhozas',
  'szavazokör',
  'szavazokor',
  'ajánlásgyűjtés',
  'ajanlas',
  'ellenzéki összefogás',
  'ellenzeki osszefogas',
  'háború',
  'haboru',
  'ukrajna',
  'brüsszel',
  'brusszel',
];
